import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import SplashContainer from '../components/SplashContainer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E.cho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.splash}>
        <SplashContainer/>
      </main>
    </div>
  )
}
