import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E.cho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          E.Cho
        </h1>

        <div className={styles.splash}>
          <div>
            <p>o</p>
            <p>|</p>
            <p>o</p>
            <p>|</p>
            <p>o</p>
          </div>
          <div>
            <p>creator</p>
            <p>&nbsp;</p>
            <p>software engineer</p>
            <p>&nbsp;</p>
            <p>artist</p>
          </div>
        </div>

        <div className={styles.card}>
          <Link href="/gallery">&gt; GALLERY</Link>
        </div>
        <div className={styles.card}>
          <Link href="/about">&gt; ABOUT ME</Link>
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      </main>

    </div>
  )
}
